### ISSUE TITLE
Allow setting data attributes with ScriptTagWriter

### ISSUE THREAD

**Issue by nickhod** [tomdcc/miniprofiler-jvm#5]
Thanks for your work on MiniProfiler JVM, we're finding it really useful.

Would it be possible to create an override of printScriptTag that takes parameters (or a parameter class) for the script tag "data-" attributes?

I can create a pull request if that helps?

**Comment by tomdcc** [comment]
Hi @nickhod! Sorry for the delay in replying.

Adding some config to control the various UI elements is planned for 0.6. Basic plan is to create a class that strongly models the various options that the UI can take via the script tag, and allow it to be set on the ProfilerProvider. ("Strongly models" meaning not just a map of strings). We can also add a parameter to the printScriptTag method that takes a set of overrides as well.

If you're interested in contributing that, it would be great. Otherwise it's next on my list, but I can't promise exactly when I'll get to it.

Thanks for the feedback, btw, I'm glad it's useful!

Cheers

Tom

**Comment by tomdcc** [comment]
@nickhod as of 0.6.1 this has now been implemented. See `io.jdev.miniprofiler.ProfilerUiConfig`. Basically you can set config globally by setting the `uiConfig` property on the `ProfilerProvider`, or by setting properties in a `miniprofiler.properties` file in the classpath. You can also pass in a `ProfilerUiConfig` object to the `ScriptTagWriter` methods if you want to set options on a case-by-case basis.
